
FT_DPCM_PTR=$c000
;this file for FamiTone2 library generated by text2data tool
	.export _after_the_rain_music_data
_after_the_rain_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; 00 : Song 2

@instruments:
	.byte $30 ; 00 : Duty 0
	.word @env0, @env1, @env1
	.byte $00
	.byte $70 ; 01 : Duty 1
	.word @env0, @env1, @env1
	.byte $00
	.byte $f0 ; 02 : Duty 3
	.word @env0, @env1, @env1
	.byte $00

@env0:
	.byte $cf,$7f,$00,$00
@env1:
	.byte $c0,$7f,$00,$01

@samples:

@song0ch0:
	.byte $fb, $01
@song0ch0loop:
	.byte $82
@song0ref5:
	.byte $6a, $8d, $60, $8d, $6a, $8d, $6e, $99, $01, $78, $99, $01, $6e, $99, $01, $6a, $99, $01, $60, $8d, $6a, $8d, $60, $8d
	.byte $6a, $8d, $6e, $8d, $6a, $8d, $60, $8d, $6a, $8d, $6e, $99, $01, $78, $99, $01, $6e, $99, $01, $6a, $99, $01, $60, $8d
	.byte $6a, $8d, $60, $8d, $6a, $8d, $6e, $8d
	.byte $ff, $38
	.word @song0ref5
	.byte $00, $f9, $f9, $f9, $f9, $95
@song0ref70:
	.byte $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9
	.byte $97, $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97
	.byte $ff, $23
	.word @song0ref70
	.byte $ff, $23
	.word @song0ref70
	.byte $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9
	.byte $97, $fd
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $84, $48, $f9, $d3, $00, $8d, $48, $8d, $00, $8d, $44, $f9, $d3, $00, $8d, $44, $8d, $00, $8d, $40, $f9, $d3, $00, $8d
	.byte $40, $8d, $00, $8d, $44, $f9, $d3, $00, $ad, $82
@song0ref174:
	.byte $42, $8d
@song0ref176:
	.byte $3e, $8d, $42, $8d, $46, $9b, $00, $48, $9b, $00, $46, $9b, $00, $42, $9b, $00, $3e, $8d, $42, $8d, $3e, $8d, $42, $8d
	.byte $3a, $8d, $42, $8d, $3e, $8d, $42, $8d, $46, $9b, $00, $48, $9b, $00, $46, $9b, $00, $42, $9b, $00, $3e, $8d, $42, $8d
	.byte $3e, $8d, $42, $8d, $3a, $8d, $3e, $8d, $3a, $8d, $3e, $8d, $42, $9b, $00, $44, $9b, $00, $42, $9b, $00, $3e, $9b, $00
	.byte $42, $8d, $3e, $8d, $3a, $f9, $ad, $00, $83, $34, $8d, $38, $8d, $3a, $8d, $3e, $9b, $00, $3a, $8d, $38, $8d, $34, $8d
	.byte $ff, $45
	.word @song0ref174
@song0ref275:
	.byte $a7, $00, $83, $3e, $9b, $00, $42, $8d, $3a, $c7, $00, $83, $3e, $8d, $3a, $8d, $36, $c7, $00, $83, $3a, $8d, $36, $8d
	.byte $32, $9d, $3a, $8d, $3e, $8d, $42, $8d, $8d, $00
	.byte $ff, $60
	.word @song0ref176
	.byte $ff, $45
	.word @song0ref174
	.byte $ff, $22
	.word @song0ref275
	.byte $ff, $60
	.word @song0ref176
	.byte $ff, $45
	.word @song0ref174
	.byte $ff, $22
	.word @song0ref275
	.byte $ff, $60
	.word @song0ref176
	.byte $ff, $45
	.word @song0ref174
	.byte $ff, $22
	.word @song0ref275
	.byte $ff, $60
	.word @song0ref176
	.byte $ff, $45
	.word @song0ref174
	.byte $ff, $22
	.word @song0ref275
	.byte $ff, $60
	.word @song0ref176
	.byte $ff, $45
	.word @song0ref174
	.byte $ff, $22
	.word @song0ref275
	.byte $ff, $60
	.word @song0ref176
	.byte $42, $8d, $3e, $8d, $42, $8d, $46, $f9, $f9, $f9, $df, $fd
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $81, $80
@song0ref374:
	.byte $6a, $8d, $60, $8d, $6a, $8d, $6e, $8d, $00, $8d, $78, $8d, $00, $8d, $6e, $8d, $00, $8d, $6a, $8d, $00, $8d, $60, $8d
	.byte $6a, $8d, $60, $8d, $6a, $8d, $6e, $8d
	.byte $ff, $1f
	.word @song0ref374
	.byte $8b, $81
	.byte $ff, $20
	.word @song0ref374
	.byte $ff, $1f
	.word @song0ref374
	.byte $8b
@song0ref418:
	.byte $81
@song0ref419:
	.byte $48, $89, $01, $48, $89, $01, $52, $89, $01, $52, $89, $01, $48, $89, $01, $48, $89, $01, $52, $89, $01, $52, $89, $01
	.byte $48, $89, $01, $48, $89, $01, $52, $89, $01, $52, $89, $01
	.byte $ff, $24
	.word @song0ref419
@song0ref458:
	.byte $48, $89, $01, $48, $89, $01, $52, $89, $01, $52, $89, $01, $48, $89, $01, $48, $89, $01, $52, $89, $01, $52, $89, $00
	.byte $81, $44, $89, $01, $44, $89, $01, $4e, $89, $01, $4e, $89, $01, $44, $89, $01, $44, $89, $01, $4e, $89, $01, $4e, $89
	.byte $01, $44, $89, $01, $44, $89, $01, $4e, $89, $01, $4e, $89, $01, $3a, $89, $01, $3a, $89, $01, $44, $89, $01, $44, $89
	.byte $01, $3a, $89, $01, $3a, $89, $01, $44, $89, $01, $44, $89, $01, $3a, $89, $01, $3a, $89, $01, $44, $89, $01, $44, $89
	.byte $01, $3a, $89, $01, $3a, $89, $01, $44, $89, $01, $44, $89, $01, $3a, $89, $01, $3a, $89, $01, $44, $89, $01, $44, $89
	.byte $00
	.byte $ff, $25
	.word @song0ref418
	.byte $ff, $24
	.word @song0ref419
	.byte $ff, $3d
	.word @song0ref458
@song0ref588:
	.byte $40, $89, $01, $40, $89, $01, $4a, $89, $01, $4a, $89, $01, $40, $89, $01, $40, $89, $01, $4a, $89, $01, $4a, $89, $01
	.byte $3c, $89, $01, $3c, $89, $01, $46, $89, $01, $46, $89, $01, $3c, $89, $01, $3c, $89, $01, $46, $89, $01, $46, $89, $01
	.byte $38, $89, $01, $38, $89, $01, $42, $89, $01, $42, $89, $00
	.byte $ff, $25
	.word @song0ref418
	.byte $ff, $24
	.word @song0ref419
	.byte $ff, $79
	.word @song0ref458
	.byte $ff, $25
	.word @song0ref418
	.byte $ff, $24
	.word @song0ref419
	.byte $ff, $3d
	.word @song0ref458
	.byte $ff, $3c
	.word @song0ref588
	.byte $ff, $25
	.word @song0ref418
	.byte $ff, $24
	.word @song0ref419
	.byte $ff, $79
	.word @song0ref458
	.byte $ff, $25
	.word @song0ref418
	.byte $ff, $24
	.word @song0ref419
	.byte $ff, $3d
	.word @song0ref458
	.byte $ff, $3c
	.word @song0ref588
	.byte $ff, $25
	.word @song0ref418
	.byte $ff, $24
	.word @song0ref419
	.byte $ff, $79
	.word @song0ref458
	.byte $ff, $25
	.word @song0ref418
	.byte $ff, $24
	.word @song0ref419
	.byte $ff, $3d
	.word @song0ref458
	.byte $ff, $3c
	.word @song0ref588
	.byte $ff, $25
	.word @song0ref418
	.byte $ff, $24
	.word @song0ref419
	.byte $ff, $79
	.word @song0ref458
	.byte $ff, $25
	.word @song0ref418
	.byte $ff, $24
	.word @song0ref419
	.byte $ff, $3d
	.word @song0ref458
	.byte $ff, $3c
	.word @song0ref588
	.byte $ff, $25
	.word @song0ref418
	.byte $ff, $24
	.word @song0ref419
	.byte $ff, $79
	.word @song0ref458
	.byte $ff, $25
	.word @song0ref418
	.byte $ff, $24
	.word @song0ref419
	.byte $ff, $3d
	.word @song0ref458
	.byte $ff, $3c
	.word @song0ref588
	.byte $ff, $25
	.word @song0ref418
	.byte $ff, $24
	.word @song0ref419
	.byte $ff, $79
	.word @song0ref458
	.byte $81, $48, $89, $01, $48, $89, $01, $52, $89, $01, $52, $89, $00, $f9, $f9, $f9, $d1, $fd
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $ff, $23
	.word @song0ref70
	.byte $ff, $23
	.word @song0ref70
	.byte $ff, $23
	.word @song0ref70
	.byte $ff, $23
	.word @song0ref70
	.byte $f9, $f9, $f9, $f9, $97, $fd
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $ff, $23
	.word @song0ref70
	.byte $ff, $23
	.word @song0ref70
	.byte $ff, $23
	.word @song0ref70
	.byte $ff, $23
	.word @song0ref70
	.byte $f9, $f9, $f9, $f9, $97, $fd
	.word @song0ch4loop